### ISSUE TITLE
Error during writing to bigWig

### ISSUE THREAD

**Issue by zchiang** [clara-parabricks/AtacWorks#134] opened 2020-03-04 19:22 UTC
Hi,

I'm also running into a separate error during writing to bigWig that reads as follows:

```
INFO:2020-03-03 21:58:42,726:AtacWorks-main] Waiting for writer to finish...
Writing the output to bigwig files
Process Process-2:
Traceback (most recent call last):
  File "/n/home01/zchiang/.conda/envs/AtacWorks/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/n/home01/zchiang/.conda/envs/AtacWorks/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/n/holylfs/LABS/buenrostro_lab/Users/zchiang/projects/AtacWorks/main.py", line 246, in writer
    bedgraph_to_bigwig(outfiles[channel], sizes_file, prefix=None,deletebg=deletebg, sort=True)
  File "/n/holylfs/LABS/buenrostro_lab/Users/zchiang/projects/AtacWorks/claragenomics/io/bigwigio.py", line 156, in bedgraph_to_bigwig
    subprocess.check_call(['sort', '-u', '-k1,1', '-k2,2n', bgfile, '-o', bgfile], env=sort_env)
  File "/n/home01/zchiang/.conda/envs/AtacWorks/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sort', '-u', '-k1,1', '-k2,2n', '/n/home01/zchiang/buenrostro_lab/projects/AtacWorks/07_ali_mouse/result/F15-015/AtacWorks_2020.03.03_21.49/F15-015_1M_pretrained.track.bedGraph', '-o', '/n/home01/zchiang/buenrostro_lab/projects/AtacWorks/07_ali_mouse/result/F15-015/AtacWorks_2020.03.03_21.49/F15-015_1M_pretrained.track.bedGraph']' died with <Signals.SIGKILL: 9>.
Inference time taken:  560.999s (Load    0.827s, Prediction  559.946s)
```

Any idea what's going on here? Please let me know if you need any more info.

**Comment by ntadimeti** [comment] 2020-03-04 21:03
@zchiang  can you tell me how big the bigwig files are that you are working with ? Would you be able to share the data and the commands you are running, so that I can reproduce the error ?

**Comment by ntadimeti** [comment] 2020-04-01 22:17
@zchiang  can you share the following information: 
1. Is a bedGraph file generated ? If so can you share the file. 
2. Were you able to generate a bigwig file separately on that file?

**Comment by ntadimeti** [comment] 2020-04-21 21:15
Hi @zchiang just checking in to see if you are still facing this problem. Please let me know if it's resolved, I'd like to close it. If you're still facing it, I'd be happy to look into it with logs and repro datasets

**Comment by ntadimeti** [comment] 2020-05-12 19:41
Closing due to no activity. Can re-open in future if necessary.

**Closed** 2020-05-12 19:42 UTC
